- name: endpointURL
  labels:
    endpoint: "https://PROMETHEUS:Baqdt8mEh0T7NjdUBZsISAv8p5CY7Dwe@som-container-server/metrics:8080" # static label
    # http://PROMETHEUS:Baqdt8mEh0T7NjdUBZsISAv8p5CY7Dwe@10.1.25.48:8080/metrics
    # "http://localhost:3000/metrics"
    
