- name: endpointURL
  labels:
    endpoint: "http://PROMETHEUS:Baqdt8mEh0T7NjdUBZsISAv8p5CY7Dwe@https://poi-som-dev.ocint.porscheinformatik.cloud/metrics" # static label
    # http://PROMETHEUS:Baqdt8mEh0T7NjdUBZsISAv8p5CY7Dwe@10.1.25.48:8080/metrics
    # "http://localhost:3000/metrics"
    
